export const FETCH_ISSUES = 'FETCH_ISSUES';
export const FETCH_ISSUES_PENDING = 'FETCH_ISSUES_PENDING';
export const FETCH_ISSUES_FULFILLED = 'FETCH_ISSUES_FULFILLED';
export const FETCH_ISSUES_REJECTED = 'FETCH_ISSUES_REJECTED';

export const DELETE_ISSUE = 'DELETE_ISSUE';
export const DELETE_ISSUE_PENDING = 'DELETE_ISSUE_PENDING';
export const DELETE_ISSUE_FULFILLED = 'DELETE_ISSUE_FULFILLED';
export const DELETE_ISSUE_REJECTED = 'DELETE_ISSUE_REJECTED';

export const CREATE_ISSUE = 'CREATE_ISSUE';
export const CREATE_ISSUE_PENDING = 'CREATE_ISSUE_PENDING';
export const CREATE_ISSUE_FULFILLED = 'CREATE_ISSUE_FULFILLED';
export const CREATE_ISSUE_REJECTED = 'CREATE_ISSUE_REJECTED';

export const UPDATE_ISSUE = 'UPDATE_ISSUE';
export const UPDATE_ISSUE_PENDING = 'UPDATE_ISSUE_PENDING';
export const UPDATE_ISSUE_FULFILLED = 'UPDATE_ISSUE_FULFILLED';
export const UPDATE_ISSUE_REJECTED = 'UPDATE_ISSUE_REJECTED';


export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_PENDING = 'DELETE_COMMENT_PENDING';
export const DELETE_COMMENT_FULFILLED = 'DELETE_COMMENT_FULFILLED';
export const DELETE_COMMENT_REJECTED = 'DELETE_COMMENT_REJECTED';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_PENDING = 'CREATE_COMMENT_PENDING';
export const CREATE_COMMENT_FULFILLED = 'CREATE_COMMENT_FULFILLED';
export const CREATE_COMMENT_REJECTED = 'CREATE_COMMENT_REJECTED';

export const UPDATE_FILTER = 'UPDATE_FILTER';
