export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CARDS_PENDING = 'FETCH_CARDS_PENDING';
export const FETCH_CARDS_FULFILLED = 'FETCH_CARDS_FULFILLED';
export const FETCH_CARDS_REJECTED = 'FETCH_CARDS_REJECTED';

export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_PENDING = 'DELETE_CARD_PENDING';
export const DELETE_CARD_FULFILLED = 'DELETE_CARD_FULFILLED';
export const DELETE_CARD_REJECTED = 'DELETE_CARD_REJECTED';
export const DELETE_CARD_SOCKET = 'DELETE_CARD_SOCKET';

export const ARCHIVE_CARD = 'ARCHIVE_CARD';
export const ARCHIVE_CARD_PENDING = 'ARCHIVE_CARD_PENDING';
export const ARCHIVE_CARD_FULFILLED = 'ARCHIVE_CARD_FULFILLED';
export const ARCHIVE_CARD_REJECTED = 'ARCHIVE_CARD_REJECTED';

export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_PENDING = 'CREATE_CARD_PENDING';
export const CREATE_CARD_FULFILLED = 'CREATE_CARD_FULFILLED';
export const CREATE_CARD_REJECTED = 'CREATE_CARD_REJECTED';
export const CREATE_CARD_SOCKET = 'CREATE_CARD_SOCKET';

export const UPDATE_CARD = 'UPDATE_CARD';
export const UPDATE_CARD_PENDING = 'UPDATE_CARD_PENDING';
export const UPDATE_CARD_FULFILLED = 'UPDATE_CARD_FULFILLED';
export const UPDATE_CARD_REJECTED = 'UPDATE_CARD_REJECTED';
export const UPDATE_CARD_SOCKET = 'UPDATE_CARD_SOCKET';


export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_PENDING = 'DELETE_COMMENT_PENDING';
export const DELETE_COMMENT_FULFILLED = 'DELETE_COMMENT_FULFILLED';
export const DELETE_COMMENT_REJECTED = 'DELETE_COMMENT_REJECTED';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_PENDING = 'CREATE_COMMENT_PENDING';
export const CREATE_COMMENT_FULFILLED = 'CREATE_COMMENT_FULFILLED';
export const CREATE_COMMENT_REJECTED = 'CREATE_COMMENT_REJECTED';

export const UPDATE_FILTER = 'UPDATE_FILTER';

export const SET_ACTIVE_CARD = 'SET_ACTIVE_CARD';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
